# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 678e45b2076c769c676c5b14ad4afba625abe039360fefe68c7cc8b4dbe0849a704071b0bc2f45b1cb8c6e6b10b787066aee6350c6881d628585b484e92c2837

test:
  secret_key_base: 3ce32563eed230ed91ae53481951e4502fda07ec6f441a82ddb7d3d1c80fb2acdb5e2f2fc57a8d4f38094177270eb94c2727be1cada2136d70d8f839b10e5c33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
